
pipeline {
    agent any

    tools {
        maven 'local_maven'
    }

    environment {
        TOMCAT_HOME = 'C:\Program Files\Apache Software Foundation\Tomcat 9.0' // Set your actual path
    }

    stages {
        stage('Build WAR') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Stop Tomcat') {
            steps {
                sh '$TOMCAT_HOME/bin/shutdown.sh || true'
            }
        }

        stage('Deploy WAR Manually') {
            steps {
                sh 'cp target/myapp.war $TOMCAT_HOME/webapps/'
            }
        }

        stage('Start Tomcat') {
            steps {
                sh '$TOMCAT_HOME/bin/startup.sh'
            }
        }
    }
}









